name: Our love, Run away, Gotta save it.

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Like it never left.

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Guess a version
        id: creat_version
        shell: bash
        run: echo "version=$(date +%s)" >> "$GITHUB_OUTPUT"

      - name: Build!
        shell: bash
        run: |
          tar -cvzf fancyindex-theme-moaeiou.tar.gz header.html footer.html style.css fancyindex.js

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ steps.creat_version.outputs.version }}
          files: fancyindex-theme-moaeiou.tar.gz
          body: |
            # 📝 Release Note
            - Fixes and improvements
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
