name: Our love, Run away, Gotta save it.

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Like it never left.

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Guess a version
        id: version
        shell: bash
        run: echo "version=$(date +%s)" >> "$GITHUB_OUTPUT"

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: "latest"

      - name: Build!
        shell: bash
        run: |
          npx --yes esbuild --minify --allow-overwrite --legal-comments=none fancyindex.js --outfile=./fancyindex.js
          npx --yes esbuild --minify --allow-overwrite --legal-comments=none style.css --outfile=./style.css
          curl -LO https://raw.githubusercontent.com/moaeiou/moaeiou/refs/heads/main/.github/workflows/format.js
          node format.js header.html ./header.html
          node format.js footer.html ./footer.html
          tar -cvf fit-moaeiou.tar.zst --zstd \
            header.html footer.html style.css fancyindex.js

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ steps.version.outputs.version }}
          files: fit-moaeiou.tar.zst
          body: |
            # 📝 Release Note
            - Fixes and improvements
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send to mirror
        uses: moaeiou/moaeiou/actions/rsync@main
        with:
          local: fit-moaeiou.tar.zst
          remote: /var/www/html/
          key: ${{ secrets.CC_LA_KEY }}
