name: Our love, Run away, Gotta save it.

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create release

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Get Version
        id: get_version
        shell: bash
        run: echo "version=${{ github.sha }}" >> "$GITHUB_OUTPUT"

      - name: Build!
        shell: bash
        run: |
          release_dir="fancyindex-theme"
          archive="${release_dir}-moaeiou.tar.gz"

          cp index.html footer.html style.css fancyindex.js "${release_dir}/"
          tar -czf "${archive}" "${release_dir}"
          tar -tzf "${archive}"

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: V${{ steps.get_version.outputs.version }}
          files: fancyindex-theme-moaeiou.tar.gz
          body: |
            # 📝 Release Note
            - Fixes and improvements
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
